<a href="https://colab.research.google.com/github/nglglhtr/tapiz/blob/master/Reliabilityv2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Download dataset from Kaggle

In [1]:
!pip install -q kaggle

In [2]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"angelagilhotra","key":"ed43085b3e82faaef4325f0240dfbaec"}'}

In [3]:
! mkdir ~/.kaggle 
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json

In [4]:
 ! kaggle datasets list

ref                                                         title                                             size  lastUpdated          downloadCount  
----------------------------------------------------------  -----------------------------------------------  -----  -------------------  -------------  
vzrenggamani/hanacaraka                                     Aksara Jawa / Hanacaraka                           9MB  2020-07-10 15:09:31             73  
vishnuvarthanrao/windows-store                              Windows Store                                     93KB  2020-07-07 12:29:07           1159  
andrewmvd/data-analyst-jobs                                 Data Analyst Jobs                                  2MB  2020-07-14 08:37:57           2024  
mrgeislinger/bart-ridership                                 BART Ridership                                   325MB  2020-07-09 22:28:07            200  
rohanrao/chai-time-data-science                             Chai Time Data Science

In [5]:
! kaggle competitions download -c fake-news fake-news

  0% 0.00/40.6k [00:00<?, ?B/s]
100% 40.6k/40.6k [00:00<00:00, 15.7MB/s]
 53% 5.00M/9.42M [00:00<00:00, 11.4MB/s]
100% 9.42M/9.42M [00:00<00:00, 19.2MB/s]
 86% 32.0M/37.0M [00:02<00:00, 6.17MB/s]
100% 37.0M/37.0M [00:02<00:00, 15.1MB/s]


In [6]:
! mkdir fake-news
! mv submit.csv test.csv.zip train.csv.zip fake-news


In [7]:
! unzip fake-news/test.csv.zip -d fake-news
! unzip fake-news/train.csv.zip -d fake-news

Archive:  fake-news/test.csv.zip
  inflating: fake-news/test.csv      
Archive:  fake-news/train.csv.zip
  inflating: fake-news/train.csv     


In [8]:
import pandas as pd 

train = pd.read_csv('./fake-news/train.csv')
test = pd.read_csv('./fake-news/test.csv')
submit = pd.read_csv('./fake-news/submit.csv')

train = train.set_index('id', drop=True)
test = test.set_index('id', drop=True)

label: 1 => unreliable

In [9]:
train.head()

title  ... label
id                                                     ...      
0   House Dem Aide: We Didn’t Even See Comey’s Let...  ...     1
1   FLYNN: Hillary Clinton, Big Woman on Campus - ...  ...     0
2                   Why the Truth Might Get You Fired  ...     1
3   15 Civilians Killed In Single US Airstrike Hav...  ...     1
4   Iranian woman jailed for fictional unpublished...  ...     1

[5 rows x 4 columns]

In [10]:
test.head()

title  ...                                               text
id                                                        ...                                                   
20800  Specter of Trump Loosens Tongues, if Not Purse...  ...  PALO ALTO, Calif.  —   After years of scorning...
20801  Russian warships ready to strike terrorists ne...  ...  Russian warships ready to strike terrorists ne...
20802  #NoDAPL: Native American Leaders Vow to Stay A...  ...  Videos #NoDAPL: Native American Leaders Vow to...
20803  Tim Tebow Will Attempt Another Comeback, This ...  ...  If at first you don’t succeed, try a different...
20804                    Keiser Report: Meme Wars (E995)  ...  42 mins ago 1 Views 0 Comments 0 Likes 'For th...

[5 rows x 3 columns]

In [11]:
submit.head()

id  label
0  20800      0
1  20801      1
2  20802      0
3  20803      1
4  20804      1

## Data Preparation

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.model_selection import train_test_split

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Embedding, GRU, LSTM, RNN, SpatialDropout1D, Bidirectional

%tensorflow_version 2.x
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))


Found GPU at: /device:GPU:0


In [13]:
train[['title', 'author']] = train[['title', 'author']].fillna(value='missing')
train=train.dropna()
train.isnull().sum()

title     0
author    0
text      0
label     0
dtype: int64

### Removing outliers

In [15]:
length = []
[length.append(len(str(text))) for text in train['text']]
train['length'] = length
train.head()

title  ... length
id                                                     ...       
0   House Dem Aide: We Didn’t Even See Comey’s Let...  ...   4930
1   FLYNN: Hillary Clinton, Big Woman on Campus - ...  ...   4160
2                   Why the Truth Might Get You Fired  ...   7692
3   15 Civilians Killed In Single US Airstrike Hav...  ...   3237
4   Iranian woman jailed for fictional unpublished...  ...    938

[5 rows x 5 columns]

In [16]:
train = train.drop(train['text'][train['length'] < 50].index, axis = 0)

In [17]:
train.shape

(20554, 5)

In [18]:
length = []
[length.append(len(str(text))) for text in test['text']]
test['length'] = length
test.head()

title  ... length
id                                                        ...       
20800  Specter of Trump Loosens Tongues, if Not Purse...  ...   8015
20801  Russian warships ready to strike terrorists ne...  ...   1559
20802  #NoDAPL: Native American Leaders Vow to Stay A...  ...   4547
20803  Tim Tebow Will Attempt Another Comeback, This ...  ...   3578
20804                    Keiser Report: Meme Wars (E995)  ...    542

[5 rows x 4 columns]

In [19]:
min(train['length']), max(train['length']), round(sum(train['length'])/len(train['length']))

(50, 142961, 4598)

In [20]:
min(test['length']), max(test['length']), round(sum(test['length'])/len(test['length']))

(1, 107014, 4650)

In [21]:
max_features = 4500

In [22]:
tokenizer = Tokenizer(num_words = max_features, filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n', lower = True, split = ' ', oov_token='<OOV>')
tokenizer.fit_on_texts(texts = train['text'])
X = tokenizer.texts_to_sequences(texts = train['text'])
X = pad_sequences(sequences = X, maxlen = max_features, padding = 'post')
X

array([[ 130,    1, 2307, ...,    0,    0,    0],
       [ 360,  115,    2, ...,    0,    0,    0],
       [ 211,    2,  738, ...,    0,    0,    0],
       ...,
       [   2,    1,    4, ...,    0,    0,    0],
       [1067,  183,    3, ...,    0,    0,    0],
       [ 743,    1,    9, ...,    0,    0,    0]], dtype=int32)

In [23]:
print(X.shape)
y = train['label'].values
print(y.shape)

(20554, 4500)
(20554,)


In [24]:
X_train, X_test, y_train, y_test = train_test_split(
    X, 
    y, 
    test_size = 0.2, random_state = 101)

In [25]:
y_train

array([1, 1, 0, ..., 0, 1, 0])

In [26]:
X_train

array([[1382, 3120, 2676, ...,    0,    0,    0],
       [ 674,   11,  369, ...,    0,    0,    0],
       [ 890,   63, 1163, ...,    0,    0,    0],
       ...,
       [1767,    1,  443, ...,    0,    0,    0],
       [  40,    3, 1085, ...,    0,    0,    0],
       [1683,    1,  139, ...,    0,    0,    0]], dtype=int32)

In [27]:
X_test

array([[ 116,   75,    9, ...,    0,    0,    0],
       [2279,    1,   19, ...,    0,    0,    0],
       [ 756,    4,  341, ...,    0,    0,    0],
       ...,
       [   1, 2415, 3464, ...,    0,    0,    0],
       [  40, 1939,    1, ...,    0,    0,    0],
       [   1,  901,   16, ...,    0,    0,    0]], dtype=int32)

In [28]:
y_test

array([1, 1, 0, ..., 0, 1, 1])

## building Sequential model

In [29]:

model = Sequential([
                    Embedding(input_dim=max_features, output_dim=120),
                    Bidirectional(LSTM(units=120, 
                         activation='tanh',
                         recurrent_activation='sigmoid',
                         unroll=False,
                         use_bias=True,
                         dropout = 0.2, 
                         recurrent_dropout = 0
                         )),
                    # Dropout(rate = 0.5),
                    Dense(units = 120,  activation = 'relu'),
                    # Dropout(rate = 0.5),
                    Dense(units = len(set(y)),  activation = 'sigmoid', name = 'output_layer')
])


model.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 120)         540000    
_________________________________________________________________
bidirectional (Bidirectional (None, 240)               231360    
_________________________________________________________________
dense (Dense)                (None, 120)               28920     
_________________________________________________________________
output_layer (Dense)         (None, 2)                 242       
Total params: 800,522
Trainable params: 800,522
Non-trainable params: 0
_________________________________________________________________


In [30]:
model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [31]:
with tf.device('/device:GPU:0'):
  model_fit = model.fit(
      X_train, y_train, epochs = 1, verbose=1)

514/514 [==============================] - 591s 1s/step - loss: 0.2281 - accuracy: 0.9041


In [32]:
from sklearn.metrics import accuracy_score
prediction = model.predict_classes(
    X_test
)
accuracy_score(y_test, prediction)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


0.9559717830211627

## Testing Model on test data

In [34]:
test = pd.read_csv('./fake-news/test.csv')
test[['title', 'author']] = test[['title', 'author']].fillna(value='missing')
test = test.set_index('id', drop=True)
test = test.fillna(' ')

In [35]:
test.shape

(5200, 3)

In [36]:
test_sequences = tokenizer.texts_to_sequences(test['text'])
test_sequences = pad_sequences(sequences = test_sequences, maxlen = max_features, padding = 'post')
test_sequences

array([[   1,    1, 3464, ...,    0,    0,    0],
       [ 230,    1, 1290, ...,    0,    0,    0],
       [1561,    1, 1663, ...,    0,    0,    0],
       ...,
       [ 192,  562,  164, ...,    0,    0,    0],
       [   1, 1042,  221, ...,    0,    0,    0],
       [ 664, 2075,  383, ...,    0,    0,    0]], dtype=int32)

In [37]:
type(test['text'])

pandas.core.series.Series

In [38]:
test_prediction = model.predict_classes(
    test_sequences
)

In [39]:
submission = pd.DataFrame({'id':test.index, 'label':test_prediction})
submission.shape

(5200, 2)

In [40]:
submission.head()

id  label
0  20800      0
1  20801      1
2  20802      1
3  20803      0
4  20804      1

In [41]:
submission.to_csv('submission.csv', index=False)

## Scratch space

In [69]:
content = 'U.S. Secretary of State John F. Kerry said Monday that he will stop in Paris later this week, amid criticism that no top American officials attended Sunday’s unity march against terrorism.\n\nKerry said he expects to arrive in Paris Thursday evening, as he heads home after a week abroad. He said he will fly to France at the conclusion of a series of meetings scheduled for Thursday in Sofia, Bulgaria. He plans to meet the next day with Foreign Minister Laurent Fabius and President Francois Hollande, then return to Washington.\n\nThe visit by Kerry, who has family and childhood ties to the country and speaks fluent French, could address some of the criticism that the United States snubbed France in its darkest hour in many years.\n\nThe French press on Monday was filled with questions about why neither President Obama nor Kerry attended Sunday’s march, as about 40 leaders of other nations did. Obama was said to have stayed away because his own security needs can be taxing on a country, and Kerry had prior commitments.\n\nAmong roughly 40 leaders who did attend was Israeli Prime Minister Benjamin Netanyahu, no stranger to intense security, who marched beside Hollande through the city streets. The highest ranking U.S. officials attending the march were Jane Hartley, the ambassador to France, and Victoria Nuland, the assistant secretary of state for European affairs. Attorney General Eric H. Holder Jr. was in Paris for meetings with law enforcement officials but did not participate in the march.\n\nKerry spent Sunday at a business summit hosted by India’s prime minister, Narendra Modi. The United States is eager for India to relax stringent laws that function as barriers to foreign investment and hopes Modi’s government will act to open the huge Indian market for more American businesses.\n\nIn a news conference, Kerry brushed aside criticism that the United States had not sent a more senior official to Paris as “quibbling a little bit.” He noted that many staffers of the American Embassy in Paris attended the march, including the ambassador. He said he had wanted to be present at the march himself but could not because of his prior commitments in India.\n\n“But that is why I am going there on the way home, to make it crystal clear how passionately we feel about the events that have taken place there,” he said.\n\n“And I don’t think the people of France have any doubts about America’s understanding of what happened, of our personal sense of loss and our deep commitment to the people of France in this moment of trauma.'
seq = tokenizer.texts_to_sequences([content])
padded = pad_sequences(seq, maxlen=max_features, padding='post')
pred_prob = model.predict(padded)
pred_class = model.predict_classes(padded)

prob = [prob*100 for prob in pred_prob]

print ('probabilities:', 
       '\nclass 0 (reliable)\t:', prob[0][0], '%',
       '\nclass 1 (unreliable)\t:', prob[0][1], '%'
       )
print ('\npredicted class:', pred_class,'\n')

## 0 -> reliable
## 1 -> unreliable

probabilities: 
class 0 (reliable)	: 97.83757 % 
class 1 (unreliable)	: 2.5534217 %

predicted class: [0] 



## Saving model & tokenizer for deployment

In [70]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 120)         540000    
_________________________________________________________________
bidirectional (Bidirectional (None, 240)               231360    
_________________________________________________________________
dense (Dense)                (None, 120)               28920     
_________________________________________________________________
output_layer (Dense)         (None, 2)                 242       
Total params: 800,522
Trainable params: 800,522
Non-trainable params: 0
_________________________________________________________________


In [77]:
tf.keras.models.save_model(
    model, '/content/saved_model', save_format='h5'
)

In [78]:
loaded_model = tf.keras.models.load_model(
    '/content/saved_model', custom_objects=None, compile=True, options=None
)

loaded_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 120)         540000    
_________________________________________________________________
bidirectional (Bidirectional (None, 240)               231360    
_________________________________________________________________
dense (Dense)                (None, 120)               28920     
_________________________________________________________________
output_layer (Dense)         (None, 2)                 242       
Total params: 800,522
Trainable params: 800,522
Non-trainable params: 0
_________________________________________________________________


In [80]:
import pickle

# saving tokenizer
with open('tokenizer.pk', 'wb') as handle:
    pickle.dump(tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [81]:
loaded_tokenizer = pickle.load(open('tokenizer.pk', 'rb'))
type(loaded_tokenizer)

keras_preprocessing.text.Tokenizer